/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif



/**
 * A wrapper class for binary data (Blob).
 */
__attribute__ ((visibility("default"))) @interface NTBinaryData : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs an empty BinaryData object.
 */
-(id)init;
/**
 * Constructs a BinaryData object from a raw byte array.<br>
 * 
 */
-(id)initWithDataPtr: (unsigned char *)dataPtr size: (unsigned int)size;
/**
 * Returns the size of the data<br>
 * @return The size of the data.
 */
-(unsigned int)size;
/**
 * Returns the data array.<br>
 * @return The data array.
 */
-(unsigned char *)getData;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

