/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package akylas.slidemenu;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import com.jeremyfeinstein.slidingmenu.lib.SlidingMenu;

@Kroll.module(name="AkylasSlidemenu", id="akylas.slidemenu")
public class AkylasSlidemenuModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "AkylasSlidemenuModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public AkylasSlidemenuModule()
	{
		super();
	}
	
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
	}
	
	@Kroll.constant public static final int STYLE_NORMAL = SlidingMenu.SLIDING_CONTENT;
	@Kroll.constant public static final int STYLE_WITH_ACTIONBAR = SlidingMenu.SLIDING_WINDOW;
	
	@Kroll.constant public static final int LEFT_VIEW = 0;
	@Kroll.constant public static final int RIGHT_VIEW = 1;

	@Kroll.constant public static final int MENU_PANNING_NONE = 0;
	@Kroll.constant public static final int MENU_PANNING_ALL_VIEWS = 1;
	@Kroll.constant public static final int MENU_PANNING_CENTER_VIEW = 2;
	@Kroll.constant public static final int MENU_PANNING_BORDERS = 3;

	
	@Kroll.constant public static final int ANIMATION_NONE = 0;
	@Kroll.constant public static final int ANIMATION_ZOOM = 1;
	@Kroll.constant public static final int ANIMATION_SCALE= 2;
	@Kroll.constant public static final int ANIMATION_SLIDEUP = 3;


	@Kroll.constant public static final String PROPERTY_TRANSITION_LEFT = "leftTransition";
	@Kroll.constant public static final String PROPERTY_TRANSITION_RIGHT = "rightTransition";
	@Kroll.constant public static final String PROPERTY_LEFT_VIEW = "leftView";
	@Kroll.constant public static final String PROPERTY_LEFT_VIEW_DISPLACEMENT = "leftViewDisplacement";
	@Kroll.constant public static final String PROPERTY_LEFT_VIEW_WIDTH = "leftViewWidth";
	@Kroll.constant public static final String PROPERTY_RIGHT_VIEW = "rightView";
	@Kroll.constant public static final String PROPERTY_RIGHT_VIEW_DISPLACEMENT = "rightViewDisplacement";
	@Kroll.constant public static final String PROPERTY_RIGHT_VIEW_WIDTH = "rightViewWidth";
	@Kroll.constant public static final String PROPERTY_PANNING_MODE = "panningMode";
	@Kroll.constant public static final String PROPERTY_CENTER_VIEW = "centerView";
	@Kroll.constant public static final String PROPERTY_FADING = "fading";
	
}

