/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package akylas.camera;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.hardware.Camera.CameraInfo;


@Kroll.module(name="AkylasCamera", id="akylas.camera")
public class AkylasCameraModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "AkylasCameraModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	@Kroll.constant
	public static final int CAMERA_FRONT = CameraInfo.CAMERA_FACING_BACK;
	@Kroll.constant
	public static final int CAMERA_BACK = CameraInfo.CAMERA_FACING_FRONT;
	
	@Kroll.constant
	public static final int QUALITY_HIGH = 2;
	@Kroll.constant
	public static final int QUALITY_MEDIUM = 1;
	@Kroll.constant
	public static final int QUALITY_LOW = 0;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public AkylasCameraModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

}

