/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package akylas.scancode;

import java.util.HashMap;
import java.util.Vector;
import java.util.regex.Pattern;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
//import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.google.zxing.BarcodeFormat;


@Kroll.module(name="AkylasScancode", id="akylas.scancode")
public class AkylasScancodeModule extends KrollModule
{

	// Standard Debugging variables
	@SuppressWarnings("unused")
	private static final String LCAT = "AkylasScancodeAndroidModule";
	@SuppressWarnings("unused")
	private static final boolean DBG = TiConfig.LOGD;
	
	static final Pattern COMMA_PATTERN = Pattern.compile(",");
	static final HashMap<String, Vector<BarcodeFormat>> STRING_TO_FORMAT;

	static {
		
		STRING_TO_FORMAT = new HashMap<String, Vector<BarcodeFormat>>();
		
		Vector<BarcodeFormat> vec = new Vector<BarcodeFormat>(1);
		vec.add(BarcodeFormat.QR_CODE);
		STRING_TO_FORMAT.put("qrcode", vec);
		
		vec = new Vector<BarcodeFormat>(1);
		vec.add(BarcodeFormat.DATA_MATRIX);
		STRING_TO_FORMAT.put("datamatrix", vec);
		
		vec = new Vector<BarcodeFormat>(1);
		vec.add(BarcodeFormat.AZTEC);
		STRING_TO_FORMAT.put("aztec", vec);
		
		vec = new Vector<BarcodeFormat>(1);
		vec.add(BarcodeFormat.EAN_8);
		STRING_TO_FORMAT.put("ean8", vec);
		
		vec = new Vector<BarcodeFormat>(1);
		vec.add(BarcodeFormat.EAN_13);
		STRING_TO_FORMAT.put("ean13", vec);
		
		vec = new Vector<BarcodeFormat>(3);
		vec.add(BarcodeFormat.CODE_39);
		vec.add(BarcodeFormat.CODE_128);
		vec.add(BarcodeFormat.ITF);
		STRING_TO_FORMAT.put("oned", vec);
		
		vec = new Vector<BarcodeFormat>(2);
		vec.add(BarcodeFormat.UPC_A);
		vec.add(BarcodeFormat.UPC_E);
		STRING_TO_FORMAT.put("upcean", vec);
	}

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public AkylasScancodeModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
//		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}
}

