/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package akylas.shapes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.util.TiUIHelper;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiUIView;

import akylas.shapes.ShapeProxy.PRoundRect;
import android.app.Activity;
import android.app.NativeActivity;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Rect;
import android.graphics.drawable.shapes.Shape;
import android.view.MotionEvent;
import android.view.View;
import android.view.View.MeasureSpec;
import android.widget.LinearLayout;

// This proxy can be created by calling Android.createExample({message: "hello world"})
@SuppressWarnings({ "unused", "unchecked", "rawtypes" })
@Kroll.proxy(name = "View", creatableInModule = AkylasShapesModule.class, propertyAccessors = {})
public class ShapeViewProxy extends TiViewProxy {
	// Standard Debugging variables
	private static final String TAG = "ShapeViewProxy";

	private static final List<String> supportedEvents = Arrays.asList(
			TiC.EVENT_CLICK, TiC.EVENT_DOUBLE_CLICK, TiC.EVENT_DOUBLE_TAP,
			TiC.EVENT_SINGLE_TAP, TiC.EVENT_LONGPRESS, TiC.EVENT_TOUCH_CANCEL, TiC.EVENT_TOUCH_END,
			TiC.EVENT_TOUCH_MOVE, TiC.EVENT_TOUCH_START);

	protected class ShapeView extends TiCompositeLayout {

		public ShapeView(Context context) {
			super(context);
			setWillNotDraw(false); // or we wont draw if we dont have a
									// background
		}

		@Override
		protected void onDraw(Canvas canvas) {
			super.onDraw(canvas);
			for (int i = 0; i < children.size(); i++) {
                KrollProxy childProxy = children.get(i);
			    if (childProxy instanceof ShapeProxy) {
			        ((ShapeProxy) childProxy).drawOnCanvas(canvas);
			    }
			}
		}
	}

	protected class TiShapeView extends TiUIView {
		protected ShapeView nativeView;
		private Rect nativeViewBounds;

		protected void onLayoutChanged(int left, int top, int right, int bottom) {
			nativeViewBounds.set(0, 0, right - left, bottom - top);
			update();
		}

		public void update() {
		    KrollProxy[] children = ShapeViewProxy.this.getChildren();
			for (int i = 0; i < children.length; i++) {
                KrollProxy childProxy = children[i];
                if (childProxy instanceof ShapeProxy) {
                    ((ShapeProxy) childProxy).onLayoutChanged(nativeView.getContext(),
                            nativeViewBounds);
                }
            }
		}

		protected void createNativeView(Activity activity) {
			nativeView = new ShapeView(activity) {
				@Override
				protected void onLayout(boolean changed, int left, int top,
						int right, int bottom) {
					super.onLayout(changed, left, top, right, bottom);
					if (changed) {
						onLayoutChanged(left, top, right, bottom);
					}
				}
			};
			setNativeView(nativeView);
			disableHWAcceleration();
		}

		public TiShapeView(final TiViewProxy proxy, Activity activity) {
			super(proxy);
			hardwareAccEnabled = false;
			nativeViewBounds = new Rect();
			createNativeView(activity);
		}

		@Override
		public void processProperties(KrollDict d) {

			super.processProperties(d);
			if (d.containsKey(AkylasShapesModule.PROPERTY_SHAPES)) {
	            ShapeViewProxy.this.add(d.get(AkylasShapesModule.PROPERTY_SHAPES), null);
	        }
			redrawNativeView();
		}

		@Override
		public void release() {
			super.release();
			nativeView = null;
		}

		public void redrawNativeView() {
			super.redrawNativeView();
		}
	}

	// Constructor
	public ShapeViewProxy() {
		super();
	}

	@Override
	public boolean fireEvent(String eventName, Object data, boolean bubbles) {
		if (supportedEvents.contains(eventName) && children.size() > 0) {
			int x = -1;
			int y = -1;
			if (data instanceof HashMap) {
				x = TiConvert.toInt((HashMap)data, TiC.PROPERTY_X);
				y = TiConvert.toInt((HashMap)data, TiC.PROPERTY_Y);
			}
			boolean handledByChildren = false;
			boolean result = false;
			KrollProxy[] children = ShapeViewProxy.this.getChildren();
            for (int i = 0; i < children.length; i++) {
                KrollProxy childProxy = children[i];
                if (childProxy instanceof ShapeProxy) {
                    handledByChildren |= ((ShapeProxy) childProxy).handleTouchEvent(eventName, data, bubbles, x, y);

                }
			}
			if (handledByChildren && bubbles) {
				return true;
			}
		}
		return super.fireEvent(eventName, data, bubbles);
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new TiShapeView(this, activity);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	@Override
	public TiUIView getOrCreateView() {
		TiUIView view = super.getOrCreateView(true);
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		Log.d(TAG, "handleCreationDict ");
		super.handleCreationDict(options);
		
	}

	@Kroll.method
	public void redraw() {
		if (view != null) {
			((TiShapeView) view).redrawNativeView();
		}
	}

	@Kroll.method
	public void update() {
		if (view != null) {
			((TiShapeView) view).update();
			((TiShapeView) view).redrawNativeView();
		}
	}

	private void addShape(ShapeProxy proxy) {
		proxy.setShapeViewProxy(this);
		redraw();
	}

	private void removeShape(ShapeProxy proxy) {
		proxy.recursiveCancelAllAnimations();
		proxy.setShapeViewProxy(null);
		redraw();
	}

	@Override
    protected void handleChildAdded(KrollProxy object, final int index) {
        if (!(object instanceof ShapeProxy)) {
            super.handleChildAdded(object, index);
            return;
        }
        ShapeProxy proxy = (ShapeProxy) object;
        addShape(proxy);
    }
    
    @Override
    protected void handleChildRemoved(KrollProxy object) {
        if (!(object instanceof ShapeProxy)) {
            super.handleChildRemoved(object);
            return;
        }
        ShapeProxy proxy = (ShapeProxy) object;
        removeShape(proxy);
    }
}