/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package akylas.opencv;

import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.proxy.TiViewProxy;

import android.app.Activity;

@Kroll.proxy(creatableInModule=AkylasOpencvModule.class)
public class OpencvViewProxy extends TiViewProxy
{
	private OpencvView cvView;
	
	// Constructor
	public OpencvViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity arg0) {
		cvView = new OpencvView(this);
		return cvView;
	}
}