/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTCartoVectorTileLayer.h"
#import "NTAssetPackage.h"

/**
 * Specialized online vector tile layer that connects to Carto online tile server.<br>
 * This layer is intended as a 'shortcut' to make using Carto online service and<br>
 * vector tiles as simple as possible.
 */
__attribute__ ((visibility("default"))) @interface NTCartoOnlineVectorTileLayer : NTCartoVectorTileLayer
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 * @param cPtr The native pointer of the instance.
 * @param cMemoryOwn The ownership flag.
 * @return The new instance.
 */
+(NTCartoOnlineVectorTileLayer*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a CartoOnlineVectorTileLayer object from a specificed base map style.<br>
 * @param style The style to use for the layer.
 */
-(id)initWithStyle: (enum NTCartoBaseMapStyle)style;
/**
 * Constructs a CartoOnlineVectorTileLayer object from a source name and specified base map style.<br>
 * @param source The tile source name. Currently only 'nutiteq' sources can be used with this constructor.<br>
 * @param style The style to use for the layer.
 */
-(id)initWithSource: (NSString*)source style: (enum NTCartoBaseMapStyle)style;
/**
 * Constructs a CartoOnlineVectorTileLayer object from a source name and style asset package.<br>
 * Style asset package defines visual style of the map and must be compatible with the source.<br>
 * @param source The tile source name. The legacy source is "nutiteq.osm", new source is "mapzen.osm" but this requires different style asset package.<br>
 * @param styleAssetPackage The style asset package (usually a zipped file or an asset)
 */
-(id)initWithSource: (NSString*)source styleAssetPackage: (NTAssetPackage*)styleAssetPackage;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

