/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTVariant.h"
#import "NTStringMap.h"
#import "NTStringVector.h"
#import "NTLayer.h"
#import "NTAssetPackage.h"
@class NTStringVariantMap;
@class NTLayerVector;

/**
 * A high-level interface for Carto Maps Service.<br>
 * The service can be used to automatically configure layers using<br>
 * anonymous map configurations or by using parametrized named maps.
 */
__attribute__ ((visibility("default"))) @interface NTCartoMapsService : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a new CartoMapsService instance with default settings.
 */
-(id)init;
/**
 * Returns the user account name used when accessing the online service.<br>
 * @return The user account name used when accessing the online service.
 */
-(NSString*)getUsername;
/**
 * Sets the user account name used when accessing the online service.<br>
 * @param username The user account name used when accessing the online service.
 */
-(void)setUsername: (NSString*)username;
/**
 * Returns the API endpoint template of the online service.<br>
 * @return The API endpoint template of the online service.
 */
-(NSString*)getAPITemplate;
/**
 * Sets the API endpoint template of the online service.<br>
 * By default cartodb.com endpoint is used. This needs to be redefined only for on-premise services.<br>
 * @param apiTemplate The API endpoint template of the online service. For example, "http://{user}.cartodb.com"
 */
-(void)setAPITemplate: (NSString*)apiTemplate;
/**
 * Returns true is the service configures<br>
 * layers as interactive by using UTF grids for click detection.<br>
 * @return True if the service configures layers as interactive.
 */
-(BOOL)isInteractive;
/**
 * Sets the interactivity flag of the layers.<br>
 * @param interactive True if layers should be configured as interactive. The default is false.
 */
-(void)setInteractive: (BOOL)interactive;
/**
 * Returns the list of authentication tokens used when accessing online service.<br>
 * @return The list of authentication tokens used when accessing online service.
 */
-(NTStringVector*)getAuthTokens;
/**
 * Sets the list of authentication tokens used when accessing online service.<br>
 * @param authTokens The list of authentication tokens used when accessing online service.
 */
-(void)setAuthTokens: (NTStringVector*)authTokens;
/**
 * Returns true if the service configures layers as vector tile layers,<br>
 * when possible. By default this is false. Vector layers<br>
 * provide much better visual quality at the expense of performance.<br>
 * @return True if vector layers should be used. False is raster layers are used.
 */
-(BOOL)isDefaultVectorLayerMode;
/**
 * Sets the service to vector layer mode or raster layer mode.<br>
 * By default service creates raster layers, but vector layers may<br>
 * provide much better visual quality at the expense of performance.<br>
 * @param vectorLayerMode True if vector layers should be used. False is raster layers are used.
 */
-(void)setDefaultVectorLayerMode: (BOOL)vectorLayerMode;
/**
 * Returns true if 'strict mode' is enabled (the service throws exceptions whenever an error is encountered).<br>
 * @return True if 'strict mode' is enabled.
 */
-(BOOL)isStrictMode;
/**
 * Sets the 'strict mode' flag.<br>
 * @param strictMode True if all errors result in exceptions. The default is false.
 */
-(void)setStrictMode: (BOOL)strictMode;
/**
 * Returns the asset package used when decoding vector tiles.<br>
 * By default, no asset package is used and null is returned.<br>
 * @return The asset package used when decoding vector tiles.
 */
-(NTAssetPackage*)getVectorTileAssetPackage;
/**
 * Sets the asset package used when decoding vector tiles.<br>
 * Asset package with fonts is needed when texts are used.<br>
 * @param assetPackage The asset package to use for vector tiles.
 */
-(void)setVectorTileAssetPackage: (NTAssetPackage*)assetPackage;
/**
 * Builds a list of layers given anonymous map configuration.<br>
 * The map configuration specification can be found in CartoDB documentation page.<br>
 * @param mapConfig The map configuration JSON deserialized as Variant type.<br>
 * @return The list of created layers.<br>
 * @throws NSException If IO error occured during the operation.
 */
-(NTLayerVector*)buildMap: (NTVariant*)mapConfig;
/**
 * Builds a list of layers given named map id and named map parameters.<br>
 * @param templateId The named map id.<br>
 * @param templateParams The map containing named map parameter names and their values.<br>
 * @return The list of created layers.<br>
 * @throws NSException If IO error occured during the operation.
 */
-(NTLayerVector*)buildNamedMap: (NSString*)templateId templateParams: (NTStringVariantMap*)templateParams;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

