/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTFeature.h"
@class NTFeatureVector;

/**
 * A collection of features.
 */
__attribute__ ((visibility("default"))) @interface NTFeatureCollection : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a FeatureCollection from a vector of features.<br>
 * @param features The features for the collection.
 */
-(id)initWithFeatures: (NTFeatureVector*)features;
/**
 * Returns the number of features in this container.<br>
 * @return The number of features.
 */
-(int)getFeatureCount;
/**
 * Returns the feature at the specified index. Index must be between 0 and getFeatureCount (exclusive).<br>
 * @return The feature at specified index.<br>
 * @throws NSException If the index is out of range.
 */
-(NTFeature*)getFeature: (int)index;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

