/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTVariant.h"
#import "NTGeometry.h"

/**
 * A feature consisting of geometry and properties
 */
__attribute__ ((visibility("default"))) @interface NTFeature : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @param object The reference object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a Feature object from geometry and properties.<br>
 * @param geometry The geometry of the feature.<br>
 * @param properties The properties of the feature.
 */
-(id)initWithGeometry: (NTGeometry*)geometry properties: (NTVariant*)properties;
/**
 * Returns the geometry of the feature.<br>
 * @return The geometry of the feature.
 */
-(NTGeometry*)getGeometry;
/**
 * Returns the properties of the feature.<br>
 * @return The properties of the feature.
 */
-(NTVariant*)getProperties;

-(void)dealloc;

@end


#import "NTVariant.h"
#import "NTGeometry.h"

__attribute__ ((visibility("default"))) @interface NTFeatureVector : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;
-(unsigned int)size;
-(unsigned int)capacity;
-(void)reserve: (unsigned int)n;
-(BOOL)isEmpty;
-(void)clear;
-(void)add: (NTFeature*)x;
-(NTFeature*)get: (int)i;
-(void)set: (int)i val: (NTFeature*)val;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

